### ISSUE TITLE
Deprecate cookeylang-ts

### ISSUE THREAD

**Issue by cursorweb** [CookeyLang/CookeyLang-TS#2]
CookeyLang TypeScript Edition was never meant to last. Now it is time to move on, and be deprecated in favor of a ruby edition!
- Maybe then Crystal/Rust edition (probably Crystal).
# Roadmap
- [ ] Finish Adding Classes
- [ ] Add stdlib
- [ ] Add require_relative-like
- [ ] Add static
- [ ] Add enums
- [ ] Add namespaces
- [ ] Add method overloading
- [ ] Good Bye

**Comment by cursorweb** [comment]
Oh yeah, then all this code gets ported to ruby so no progress is lost!

**Comment by firefish111** [comment]
Hmm, [hits compile], oh, its all js again!

**Comment by RaidTheWeb** [comment]
hm, ruby? not sure if that's much of an improvement...

**Comment by RaidTheWeb** [comment]
oops
